graph TD
    N0[demo.py]
    N1[demo_azure.py]
    N2[demo_bedrock.py]
    N3[demo_local.py]
    N4[demo_openai.py]
    N5[main.py]
    N6[main_azure.py]
    N7[main_dpr.py]
    N8[setup.py]
    N9[__init__.py]
    N10[__init__.py]
    N11[base.py]
    N12[Cohere.py]
    N13[Contriever.py]
    N14[GritLM.py]
    N15[NVEmbedV2.py]
    N16[OpenAI.py]
    N17[Transformers.py]
    N18[VLLM.py]
    N19[embedding_store.py]
    N20[__init__.py]
    N21[base.py]
    N22[qa_eval.py]
    N23[retrieval_eval.py]
    N24[HippoRAG.py]
    N25[__init__.py]
    N26[openie_openai.py]
    N27[openie_transformers_offline.py]
    N28[openie_vllm_offline.py]
    N29[__init__.py]
    N30[base.py]
    N31[bedrock_llm.py]
    N32[openai_gpt.py]
    N33[transformers_llm.py]
    N34[transformers_offline.py]
    N35[vllm_offline.py]
    N36[__init__.py]
    N37[filter_default_prompt.py]
    N38[linking.py]
    N39[prompt_template_manager.py]
    N40[__init__.py]
    N41[ircot_hotpotqa.py]
    N42[ircot_musique.py]
    N43[ner.py]
    N44[ner_query.py]
    N45[rag_qa_musique.py]
    N46[triple_extraction.py]
    N47[rerank.py]
    N48[StandardRAG.py]
    N49[__init__.py]
    N50[config_utils.py]
    N51[embed_utils.py]
    N52[eval_utils.py]
    N53[llm_utils.py]
    N54[logging_utils.py]
    N55[misc_utils.py]
    N56[qa_utils.py]
    N57[typing.py]
    N58[test_transformers.py]
    N59[tests_azure.py]
    N60[tests_local.py]
    N61[tests_openai.py]