graph TD
    N0[IosLinkOrderDiagnostics.cs]
    N1[PackageVersionEmbedder.cs]
    N2[install.py]
    N3[AudioFrame.cs]
    N4[AudioStream.cs]
    N5[BasicAudioSource.cs]
    N6[CameraVideoSource.cs]
    N7[DataStream.cs]
    N8[DataTrack.cs]
    N9[E2EE.cs]
    N10[AudioProbe.cs]
    N11[AudioResampler.cs]
    N12[Constants.cs]
    N13[FFIClient.cs]
    N14[FFIEvents.cs]
    N15[FfiRequestExtensions.cs]
    N16[FfiResponseWrap.cs]
    N17[IFFIClient.cs]
    N18[IMultiPool.cs]
    N19[ArrayMemoryPool.cs]
    N20[IMemoryPool.cs]
    N21[MemoryWrap.cs]
    N22[ThreadSafeObjectPool.cs]
    N23[Pools.cs]
    N24[ThreadSafeMultiPool.cs]
    N25[FFIBridge.cs]
    N26[FFIBridgeExtensions.cs]
    N27[FfiRequestWrap.cs]
    N28[IFFIBridge.cs]
    N29[SmartWrap.cs]
    N30[FFIHandle.cs]
    N31[MonoBehaviourContext.cs]
    N32[NativeMethods.cs]
    N33[PackageVersion.cs]
    N34[RingBuffer.cs]
    N35[ThreadSafeQueue.cs]
    N36[Utils.cs]
    N37[YieldInstruction.cs]
    N38[MicrophoneSource.cs]
    N39[Participant.cs]
    N40[AudioFrame.cs]
    N41[DataStream.cs]
    N42[DataTrack.cs]
    N43[E2Ee.cs]
    N44[Ffi.cs]
    N45[Handle.cs]
    N46[Participant.cs]
    N47[Room.cs]
    N48[Rpc.cs]
    N49[Stats.cs]
    N50[Track.cs]
    N51[TrackPublication.cs]
    N52[VideoFrame.cs]
    N53[Room.cs]
    N54[Rpc.cs]
    N55[RtcAudioSource.cs]
    N56[RtcSource.cs]
    N57[RtcVideoSource.cs]
    N58[ScreenVideoSource.cs]
    N59[TextureVideoSource.cs]
    N60[Track.cs]
    N61[TrackPublication.cs]
    N62[YuvToRgbConverter.cs]
    N63[VideoFrame.cs]
    N64[VideoStream.cs]
    N65[WebCameraSource.cs]
    N66[RoomManager.cs]
    N67[BuildPostProcessor.cs]
    N68[MaterialIconEditor.cs]
    N69[MaterialIconSelectionWindow.cs]
    N70[MenuOptions.cs]
    N71[MaterialIcon.cs]
    N72[LivekitSamples.cs]
    N73[ResizeTextureController.cs]
    N74[ScrollingLog.cs]
    N75[MediaStreamLifetimeTests.cs]
    N76[UsageStrictTests.cs]
    N77[DataStreamTests.cs]
    N78[DataTrackTests.cs]
    N79[LocalParticipantTests.cs]
    N80[RoomTests.cs]
    N81[AccessToken.cs]
    N82[Expectation.cs]
    N83[JsonWebToken.cs]
    N84[TestRoomContext.cs]