graph TD
    N0[__init__.py]
    N1[rearrange.py]
    N2[utils.py]
    N3[__init__.py]
    N4[datasets_common.py]
    N5[preprocess_r3d_file.py]
    N6[replica_constants.py]
    N7[save_record3d.py]
    N8[__init__.py]
    N9[llava_model.py]
    N10[build_scenegraph_cfslam.py]
    N11[GPTPrompt.py]
    N12[merge_duplicate_objects.py]
    N13[__init__.py]
    N14[animate_mapping_interactive.py]
    N15[animate_mapping_save.py]
    N16[eval_replica_semseg.py]
    N17[generate_ai2thor_dataset.py]
    N18[generate_gsa_results.py]
    N19[run_post_filter_merge.py]
    N20[run_slam_rgb.py]
    N21[reader.py]
    N22[SensorData.py]
    N23[streamlined_detections.py]
    N24[visualize_cfslam_interact_llava.py]
    N25[visualize_cfslam_results.py]
    N26[__init__.py]
    N27[cfslam_pipeline_batch.py]
    N28[mapping.py]
    N29[slam_classes.py]
    N30[streamlined_mapping.py]
    N31[utils.py]
    N32[__init__.py]
    N33[ai2thor.py]
    N34[eval.py]
    N35[general_utils.py]
    N36[geometry.py]
    N37[image.py]
    N38[ious.py]
    N39[model_utils.py]
    N40[vis.py]
    N41[setup.py]