graph TD
    N0[conftest.py]
    N1[example_graph_usage.py]
    N2[langchain_example.py]
    N3[llamaindex_example.py]
    N4[context-hook.js]
    N5[memory-list-skill.js]
    N6[memory-profile-skill.js]
    N7[memory-recall-skill.js]
    N8[memory-remember-skill.js]
    N9[memory-reset-skill.js]
    N10[post-recall-hook.js]
    N11[__init__.py]
    N12[chat_message_history.py]
    N13[__init__.py]
    N14[test_chat_message_history.py]
    N15[test_security.py]
    N16[__init__.py]
    N17[base.py]
    N18[__init__.py]
    N19[test_chat_store.py]
    N20[test_security.py]
    N21[__init__.py]
    N22[crewai_memory.py]
    N23[langchain_memory.py]
    N24[build_entry.py]
    N25[generate-thumbnails.py]
    N26[validation.js]
    N27[postinstall-interactive.js]
    N28[postinstall.js]
    N29[postinstall_binary.js]
    N30[prepack.js]
    N31[preuninstall.js]
    N32[release_manifest.py]
    N33[__init__.py]
    N34[__init__.py]
    N35[mathematical_dna.py]
    N36[signer.py]
    N37[watermark.py]
    N38[__init__.py]
    N39[commands.py]
    N40[context_commands.py]
    N41[daemon.py]
    N42[db_migrate.py]
    N43[doctor_cmd.py]
    N44[escape_hatch.py]
    N45[ingest_cmd.py]
    N46[json_output.py]
    N47[main.py]
    N48[migrate_cmd.py]
    N49[pending_store.py]
    N50[post_install.py]
    N51[service_installer.py]
    N52[setup_wizard.py]
    N53[version_banner.py]
    N54[wizard_v3426_options.py]
    N55[__init__.py]
    N56[blast_radius.py]
    N57[__init__.py]
    N58[entity_resolver.py]
    N59[event_listeners.py]
    N60[fact_enricher.py]
    N61[hebbian_linker.py]
    N62[temporal_checker.py]
    N63[changes.py]
    N64[communities.py]
    N65[config.py]
    N66[database.py]
    N67[__init__.py]
    N68[python.py]
    N69[typescript.py]
    N70[flows.py]
    N71[git_hooks.py]
    N72[graph_engine.py]
    N73[graph_store.py]
    N74[incremental.py]
    N75[models.py]
    N76[parser.py]
    N77[resolver.py]
    N78[search.py]
    N79[service.py]
    N80[watcher.py]
    N81[__init__.py]
    N82[abac.py]
    N83[audit.py]
    N84[eu_ai_act.py]
    N85[gdpr.py]
    N86[lifecycle.py]
    N87[retention.py]
    N88[scheduler.py]
    N89[__init__.py]
    N90[clock_monitor.py]
    N91[config.py]
    N92[consolidation_engine.py]
    N93[context_cache.py]
    N94[db_pool.py]
    N95[embedding_worker.py]
    N96[embeddings.py]
    N97[engine.py]
    N98[engine_capabilities.py]
    N99[engine_lock.py]
    N100[engine_wiring.py]
    N101[error_catalog.py]
    N102[error_envelope.py]
    N103[fact_consolidator.py]
    N104[file_lock.py]
    N105[graph_analyzer.py]
    N106[graph_pruner.py]
    N107[health_monitor.py]
    N108[hooks.py]
    N109[loop_watchdog.py]
    N110[maintenance.py]
    N111[maintenance_scheduler.py]
    N112[modes.py]
    N113[ollama_embedder.py]
    N114[platform_utils.py]
    N115[priority_queue.py]
    N116[profiles.py]
    N117[queue_consumer.py]
    N118[queue_dispatcher.py]
    N119[ram_lock.py]
    N120[rate_limit.py]
    N121[recall_gate.py]
    N122[recall_pipeline.py]
    N123[recall_queue.py]
    N124[recall_worker.py]
    N125[registry.py]
    N126[reranker_worker.py]
    N127[safe_fs.py]
    N128[security_primitives.py]
    N129[shadow_router.py]
    N130[slm_disabled.py]
    N131[slmignore.py]
    N132[store_pipeline.py]
    N133[summarizer.py]
    N134[tier_manager.py]
    N135[topic_signature.py]
    N136[worker_pool.py]
    N137[__init__.py]
    N138[activation_guided_quantization.py]
    N139[eap_scheduler.py]
    N140[ebbinghaus_langevin_coupling.py]
    N141[fisher_langevin_coupling.py]
    N142[__init__.py]
    N143[auto_linker.py]
    N144[cognitive_consolidator.py]
    N145[consolidator.py]
    N146[context_generator.py]
    N147[emotional.py]
    N148[entity_resolver.py]
    N149[entropy_gate.py]
    N150[fact_extractor.py]
    N151[foresight.py]
    N152[graph_builder.py]
    N153[observation_builder.py]
    N154[scene_builder.py]
    N155[signal_inference.py]
    N156[temporal_parser.py]
    N157[temporal_validator.py]
    N158[type_router.py]
    N159[__init__.py]
    N160[blind_verifier.py]
    N161[budget.py]
    N162[evolution_store.py]
    N163[llm_dispatch.py]
    N164[mutation_generator.py]
    N165[skill_evolver.py]
    N166[triggers.py]
    N167[types.py]
    N168[__init__.py]
    N169[_outcome_common.py]
    N170[adapter_base.py]
    N171[antigravity_adapter.py]
    N172[auto_capture.py]
    N173[auto_invoker.py]
    N174[auto_parameterize.py]
    N175[auto_recall.py]
    N176[auto_recall_hook.py]
    N177[claude_code_hooks.py]
    N178[context_payload.py]
    N179[copilot_adapter.py]
    N180[cross_platform_connector.py]
    N181[cursor_adapter.py]
    N182[hook_daemon.py]
    N183[hook_handlers.py]
    N184[ide_connector.py]
    N185[post_tool_async_hook.py]
    N186[post_tool_outcome_hook.py]
    N187[prewarm_auth.py]
    N188[rules_engine.py]
    N189[session_registry.py]
    N190[stop_outcome_hook.py]
    N191[sync_loop.py]
    N192[user_prompt_hook.py]
    N193[user_prompt_rehash_hook.py]
    N194[__init__.py]
    N195[auth_middleware.py]
    N196[backup.py]
    N197[cache_manager.py]
    N198[cloud_backup.py]
    N199[event_bus.py]
    N200[heartbeat_monitor.py]
    N201[pid_manager.py]
    N202[process_reaper.py]
    N203[rate_limiter.py]
    N204[webhook_dispatcher.py]
    N205[__init__.py]
    N206[adapter_manager.py]
    N207[base_adapter.py]
    N208[calendar_adapter.py]
    N209[credentials.py]
    N210[gmail_adapter.py]
    N211[parsers.py]
    N212[transcript_adapter.py]
    N213[__init__.py]
    N214[adaptive.py]
    N215[arm_catalog.py]
    N216[assertion_miner.py]
    N217[bandit.py]
    N218[bandit_cache.py]
    N219[behavioral.py]
    N220[behavioral_listener.py]
    N221[bootstrap.py]
    N222[consolidation_cycle.py]
    N223[consolidation_quantization_worker.py]
    N224[consolidation_worker.py]
    N225[cross_project.py]
    N226[database.py]
    N227[dedup_hnsw.py]
    N228[engagement.py]
    N229[ensemble.py]
    N230[entity_compiler.py]
    N231[fact_outcome_joins.py]
    N232[features.py]
    N233[feedback.py]
    N234[forgetting_scheduler.py]
    N235[hnsw_dedup.py]
    N236[labeler.py]
    N237[legacy_migration.py]
    N238[memory_merge.py]
    N239[model_cache.py]
    N240[model_rollback.py]
    N241[outcome_queue.py]
    N242[outcomes.py]
    N243[pattern_miner.py]
    N244[pattern_miner_constants.py]
    N245[project_context.py]
    N246[quantization_scheduler.py]
    N247[ranker.py]
    N248[ranker_common.py]
    N249[ranker_retrain_legacy.py]
    N250[ranker_retrain_online.py]
    N251[reward.py]
    N252[reward_archive.py]
    N253[reward_boost.py]
    N254[reward_proxy.py]
    N255[shadow_test.py]
    N256[signal_worker.py]
    N257[signals.py]
    N258[skill_performance_miner.py]
    N259[source_quality.py]
    N260[trigram_index.py]
    N261[workflows.py]
    N262[__init__.py]
    N263[backbone.py]
    N264[__init__.py]
    N265[ebbinghaus.py]
    N266[fisher.py]
    N267[fisher_quantized.py]
    N268[hopfield.py]
    N269[langevin.py]
    N270[polar_quant.py]
    N271[qjl.py]
    N272[sheaf.py]
    N273[turbo_quant.py]
    N274[__init__.py]
    N275[_daemon_proxy.py]
    N276[_pool_adapter.py]
    N277[resources.py]
    N278[server.py]
    N279[shared.py]
    N280[tools.py]
    N281[tools_active.py]
    N282[tools_code_graph.py]
    N283[tools_context.py]
    N284[tools_core.py]
    N285[tools_evolution.py]
    N286[tools_learning.py]
    N287[tools_mesh.py]
    N288[tools_v28.py]
    N289[tools_v3.py]
    N290[tools_v33.py]
    N291[__init__.py]
    N292[broker.py]
    N293[__init__.py]
    N294[v3_4_25_to_v3_4_26.py]
    N295[__init__.py]
    N296[pattern_extractor.py]
    N297[pii_filter.py]
    N298[prompt_injector.py]
    N299[prompt_lifecycle.py]
    N300[soft_prompt_generator.py]
    N301[__init__.py]
    N302[agentic.py]
    N303[ann_index.py]
    N304[bm25_channel.py]
    N305[bridge_discovery.py]
    N306[channel_registry.py]
    N307[engine.py]
    N308[entity_channel.py]
    N309[forgetting_filter.py]
    N310[fusion.py]
    N311[hopfield_channel.py]
    N312[profile_channel.py]
    N313[quantization_aware_search.py]
    N314[reranker.py]
    N315[semantic_channel.py]
    N316[spreading_activation.py]
    N317[strategy.py]
    N318[temporal_channel.py]
    N319[vector_store.py]
    N320[__init__.py]
    N321[api.py]
    N322[bandit_loops.py]
    N323[__init__.py]
    N324[security_headers.py]
    N325[__init__.py]
    N326[adapters.py]
    N327[agents.py]
    N328[backup.py]
    N329[behavioral.py]
    N330[brain.py]
    N331[chat.py]
    N332[compliance.py]
    N333[data_io.py]
    N334[entity.py]
    N335[events.py]
    N336[evolution.py]
    N337[helpers.py]
    N338[ingest.py]
    N339[insights.py]
    N340[learning.py]
    N341[lifecycle.py]
    N342[memories.py]
    N343[mesh.py]
    N344[prewarm.py]
    N345[profiles.py]
    N346[stats.py]
    N347[tiers.py]
    N348[timeline.py]
    N349[token.py]
    N350[v3_api.py]
    N351[ws.py]
    N352[security_middleware.py]
    N353[ui.py]
    N354[unified_daemon.py]
    N355[__init__.py]
    N356[access_control.py]
    N357[access_log.py]
    N358[database.py]
    N359[embedding_migrator.py]
    N360[migration_runner.py]
    N361[migration_v33.py]
    N362[__init__.py]
    N363[M001_add_signal_features_columns.py]
    N364[M002_model_state_history.py]
    N365[M003_migration_log.py]
    N366[M004_cross_platform_sync_log.py]
    N367[M005_bandit_tables.py]
    N368[M006_action_outcomes_reward.py]
    N369[M007_pending_outcomes.py]
    N370[M009_model_lineage.py]
    N371[M010_evolution_config.py]
    N372[M011_archive_and_merge.py]
    N373[M012_shadow_observations.py]
    N374[M013_bi_temporal_columns.py]
    N375[migrations.py]
    N376[models.py]
    N377[quantized_store.py]
    N378[schema.py]
    N379[schema_code_graph.py]
    N380[schema_v32.py]
    N381[schema_v3410.py]
    N382[schema_v3411.py]
    N383[schema_v343.py]
    N384[schema_v347.py]
    N385[v2_migrator.py]
    N386[__init__.py]
    N387[gate.py]
    N388[provenance.py]
    N389[scorer.py]
    N390[signals.py]
    N391[agents.js]
    N392[auto-settings.js]
    N393[brain.js]
    N394[clusters.js]
    N395[compliance.js]
    N396[core.js]
    N397[dashboard.js]
    N398[events.js]
    N399[fact-detail.js]
    N400[feedback.js]
    N401[graph-event-bus.js]
    N402[graph-filters.js]
    N403[graph-ui.js]
    N404[ide-status.js]
    N405[init.js]
    N406[knowledge-graph.js]
    N407[lifecycle.js]
    N408[math-health.js]
    N409[memories.js]
    N410[memory-chat.js]
    N411[memory-timeline.js]
    N412[modal.js]
    N413[ng-entities.js]
    N414[ng-health.js]
    N415[ng-ingestion.js]
    N416[ng-mesh.js]
    N417[ng-shell.js]
    N418[ng-skills.js]
    N419[profiles.js]
    N420[quick-actions.js]
    N421[recall-lab.js]
    N422[search.js]
    N423[settings.js]
    N424[timeline.js]
    N425[trust-dashboard.js]
    N426[bootstrap.bundle.min.js]
    N427[d3.v7.min.js]
    N428[graphology-library.min.js]
    N429[graphology.umd.min.js]
    N430[sigma.min.js]
    N431[__init__.py]
    N432[__init__.py]
    N433[test_chaos_queue.py]
    N434[conftest.py]
    N435[__init__.py]
    N436[benchmark_data.py]
    N437[__init__.py]
    N438[test_entity_compilation.py]
    N439[test_health_monitor.py]
    N440[test_ingestion.py]
    N441[test_mesh.py]
    N442[test_unified_daemon.py]
    N443[test_postinstall_validation.js]
    N444[__init__.py]
    N445[test_queue_invariants.py]
    N446[__init__.py]
    N447[conftest.py]
    N448[test_antigravity_adapter.py]
    N449[test_content_builder.py]
    N450[test_copilot_adapter.py]
    N451[test_cross_platform_connector.py]
    N452[test_cursor_adapter.py]
    N453[test_extra_coverage.py]
    N454[test_sync_loop.py]
    N455[__init__.py]
    N456[conftest.py]
    N457[test_api_associations.py]
    N458[test_api_auto_invoke.py]
    N459[test_api_consolidation.py]
    N460[test_api_v33.py]
    N461[test_brain_endpoint.py]
    N462[test_dashboard_phase_truth.py]
    N463[test_engine_lifecycle.py]
    N464[test_s9_w4_brain_contract.py]
    N465[test_token_endpoint.py]
    N466[test_worker_idle_config.py]
    N467[test_auto_hooks.py]
    N468[test_behavioral_full.py]
    N469[__init__.py]
    N470[chart_export.py]
    N471[evo_memory.py]
    N472[evo_memory_multiseed.py]
    N473[__init__.py]
    N474[generate_synthetic_fixture.py]
    N475[__init__.py]
    N476[run_locomo.py]
    N477[score.py]
    N478[test_evo_memory_runner.py]
    N479[test_hook_cold_start.py]
    N480[__init__.py]
    N481[conftest.py]
    N482[test_dispatcher_fallback.py]
    N483[test_entry_generator.py]
    N484[test_manifest_generator.py]
    N485[__init__.py]
    N486[test_stage5b_gate.py]
    N487[test_claude_hooks.py]
    N488[test_cli.py]
    N489[test_cli_json.py]
    N490[__init__.py]
    N491[test_connect_and_prestage.py]
    N492[test_db_migrate.py]
    N493[test_doctor.py]
    N494[test_escape_hatch.py]
    N495[test_version_banner.py]
    N496[test_wizard_v3426_options.py]
    N497[test_cli_v33.py]
    N498[__init__.py]
    N499[conftest.py]
    N500[sample_python.py]
    N501[sample_typescript.ts]
    N502[test_blast_radius.py]
    N503[test_changes.py]
    N504[test_communities.py]
    N505[test_config.py]
    N506[test_database.py]
    N507[test_entity_resolver.py]
    N508[test_event_listeners.py]
    N509[test_extractor_python.py]
    N510[test_extractor_typescript.py]
    N511[test_fact_enricher.py]
    N512[test_flows.py]
    N513[test_git_hooks.py]
    N514[test_graph_engine.py]
    N515[test_graph_store.py]
    N516[test_hebbian_linker.py]
    N517[test_incremental.py]
    N518[test_mcp_tools.py]
    N519[test_models.py]
    N520[test_parser.py]
    N521[test_resolver.py]
    N522[test_schema.py]
    N523[test_search.py]
    N524[test_service.py]
    N525[test_temporal_checker.py]
    N526[test_watcher.py]
    N527[__init__.py]
    N528[test_eu_ai_act.py]
    N529[test_gdpr.py]
    N530[test_lifecycle.py]
    N531[test_compliance_full.py]
    N532[test_config_system.py]
    N533[__init__.py]
    N534[test_clock_monitor.py]
    N535[test_config.py]
    N536[test_consolidation_engine.py]
    N537[test_context_cache.py]
    N538[test_core_memory_blocks.py]
    N539[test_db_pool.py]
    N540[test_embedding_fallback.py]
    N541[test_engine_capabilities.py]
    N542[test_engine_lock.py]
    N543[test_engine_recall_path.py]
    N544[test_engine_session_lifecycle.py]
    N545[test_engine_store_path.py]
    N546[test_error_catalog.py]
    N547[test_error_envelope.py]
    N548[test_file_lock.py]
    N549[test_graph_analyzer.py]
    N550[test_langevin_init.py]
    N551[test_loop_watchdog.py]
    N552[test_migration_daemon_safety.py]
    N553[test_migration_v3_4_26.py]
    N554[test_modes.py]
    N555[test_ollama_embedder.py]
    N556[test_openai_embeddings.py]
    N557[test_platform_utils.py]
    N558[test_priority_queue.py]
    N559[test_profiles.py]
    N560[test_queue_consumer.py]
    N561[test_queue_dispatcher.py]
    N562[test_ram_lock.py]
    N563[test_rate_limit.py]
    N564[test_recall_markers.py]
    N565[test_recall_queue.py]
    N566[test_registry.py]
    N567[test_s9_dash_recall_perf.py]
    N568[test_s9_w2_security.py]
    N569[test_safe_fs.py]
    N570[test_security_primitives.py]
    N571[test_shadow_router.py]
    N572[test_silent_failure_elevation.py]
    N573[test_slm_disabled.py]
    N574[test_slmignore.py]
    N575[test_stage8_ram_lock_parent_perms.py]
    N576[test_topic_signature.py]
    N577[__init__.py]
    N578[test_eap_scheduler.py]
    N579[test_ebbinghaus_langevin.py]
    N580[test_sagq.py]
    N581[__init__.py]
    N582[test_auto_linker.py]
    N583[test_cognitive_consolidator.py]
    N584[test_consolidator.py]
    N585[test_context_generator.py]
    N586[test_emotional.py]
    N587[test_entity_resolver.py]
    N588[test_entropy_gate.py]
    N589[test_fact_extractor.py]
    N590[test_foresight.py]
    N591[test_graph_builder.py]
    N592[test_observation_builder.py]
    N593[test_scene_builder.py]
    N594[test_signal_inference.py]
    N595[test_temporal_filter.py]
    N596[test_temporal_parser.py]
    N597[test_temporal_validator.py]
    N598[test_type_router.py]
    N599[test_engine_hooks.py]
    N600[test_event_bus.py]
    N601[__init__.py]
    N602[test_evolution.py]
    N603[test_evolution_budget.py]
    N604[test_llm_dispatch.py]
    N605[test_skill_evolver_firing.py]
    N606[test_features.py]
    N607[test_final_locomo_mini.py]
    N608[test_hook_handlers.py]
    N609[__init__.py]
    N610[test_auto_invoker.py]
    N611[test_auto_parameterize.py]
    N612[test_auto_recall_hook.py]
    N613[test_fok_gating.py]
    N614[test_hook_daemon.py]
    N615[test_hook_handlers.py]
    N616[test_hooks_callable_injection.py]
    N617[test_multi_signal_scoring.py]
    N618[test_outcome_hooks.py]
    N619[test_prewarm_auth.py]
    N620[test_stage8_outcome_common_security.py]
    N621[test_stage8_post_tool_marker_regex.py]
    N622[test_user_prompt_hook_entity_detection.py]
    N623[test_ide_connector.py]
    N624[test_infra.py]
    N625[__init__.py]
    N626[test_async_remember_e2e.py]
    N627[test_async_remember_materializer.py]
    N628[test_cross_platform_learning.py]
    N629[test_e2e.py]
    N630[test_e2e_v32.py]
    N631[test_e2e_v33.py]
    N632[test_encoding_wiring.py]
    N633[test_mode_b_ollama.py]
    N634[test_trust_compliance_wiring.py]
    N635[test_upgrade_v3_4_25_to_v3_4_26.py]
    N636[__init__.py]
    N637[_signal_fixtures.py]
    N638[test_adaptive.py]
    N639[test_arm_catalog.py]
    N640[test_bandit_core.py]
    N641[test_bandit_in_recall.py]
    N642[test_bandit_supplementary.py]
    N643[test_behavioral.py]
    N644[test_consolidation_online_retrain_wiring.py]
    N645[test_consolidation_quantization_worker.py]
    N646[test_engagement_reward_model.py]
    N647[test_ensemble.py]
    N648[test_f4a_refactor.py]
    N649[test_fact_outcome_joins.py]
    N650[test_feature_extraction_wired.py]
    N651[test_forgetting_scheduler.py]
    N652[test_hnsw_dedup.py]
    N653[test_labeler.py]
    N654[test_learning_db.py]
    N655[test_lightgbm_training.py]
    N656[test_memory_merge.py]
    N657[test_online_retrain.py]
    N658[test_outcomes.py]
    N659[test_quant_scheduler.py]
    N660[test_ranker_v2.py]
    N661[test_retention_sweep.py]
    N662[test_reward_gated_archive.py]
    N663[test_reward_proxy.py]
    N664[test_s9_dash_orphan_entity.py]
    N665[test_s9_dash_outcome_queue.py]
    N666[test_s9_w1_lld10_wiring.py]
    N667[test_s9_w6_skeptic.py]
    N668[test_shadow_test.py]
    N669[test_signal_worker.py]
    N670[test_signals_pipeline.py]
    N671[test_stage8_reward_archive_payload_cap.py]
    N672[test_stage8_reward_signal_typecheck.py]
    N673[test_stage8_trigram_rebuild_bound.py]
    N674[test_trigram_index.py]
    N675[test_learning_advanced.py]
    N676[test_learning_collectors.py]
    N677[test_llm_provider.py]
    N678[__init__.py]
    N679[test_ebbinghaus.py]
    N680[test_fisher.py]
    N681[test_fisher_quantized.py]
    N682[test_hopfield.py]
    N683[test_langevin.py]
    N684[test_polar_quant.py]
    N685[test_qjl.py]
    N686[test_sheaf.py]
    N687[test_turbo_quant.py]
    N688[__init__.py]
    N689[test_mcp_daemon_proxy.py]
    N690[test_mcp_light_engine.py]
    N691[test_mcp_pool_adapter.py]
    N692[test_mcp_recall_tool.py]
    N693[test_mcp_remember_tool.py]
    N694[test_mcp_session_init_tool.py]
    N695[test_mcp_tool_annotations.py]
    N696[test_mcp_tools_registration.py]
    N697[test_mcp_v33_tools.py]
    N698[test_prestage_context_tool.py]
    N699[test_mcp_server.py]
    N700[test_migration.py]
    N701[__init__.py]
    N702[test_pattern_extractor.py]
    N703[test_pii_filter.py]
    N704[test_prompt_injector.py]
    N705[test_prompt_lifecycle.py]
    N706[test_soft_prompt_generator.py]
    N707[test_post_install.py]
    N708[__init__.py]
    N709[test_interactive_installer.py]
    N710[__init__.py]
    N711[conftest.py]
    N712[test_heartbeat_monitor.py]
    N713[test_pid_manager.py]
    N714[test_process_reaper.py]
    N715[test_ranker.py]
    N716[__init__.py]
    N717[test_agentic.py]
    N718[test_ann_index.py]
    N719[test_ann_index_lifecycle.py]
    N720[test_bm25_channel.py]
    N721[test_engine.py]
    N722[test_entity_channel.py]
    N723[test_forgetting_filter.py]
    N724[test_fusion.py]
    N725[test_hopfield_channel.py]
    N726[test_quant_aware_search.py]
    N727[test_reranker.py]
    N728[test_retrieval_integration.py]
    N729[test_semantic_channel.py]
    N730[test_semantic_channel_performance.py]
    N731[test_semantic_channel_with_vec.py]
    N732[test_spreading_activation.py]
    N733[test_strategy.py]
    N734[test_temporal_channel.py]
    N735[test_vector_store.py]
    N736[__init__.py]
    N737[test_headers.py]
    N738[test_preference_redaction.py]
    N739[__init__.py]
    N740[test_access_control.py]
    N741[test_access_log.py]
    N742[test_concurrent_db.py]
    N743[test_database.py]
    N744[test_embedding_migrator.py]
    N745[test_migration_runner.py]
    N746[test_migrations.py]
    N747[test_migrations_content.py]
    N748[test_models.py]
    N749[test_quantized_store.py]
    N750[test_s9_w1_data_integrity.py]
    N751[test_schema.py]
    N752[__init__.py]
    N753[test_provenance.py]
    N754[test_scorer.py]
    N755[test_trust_full.py]
    N756[__init__.py]
    N757[test_brain_render.py]
    N758[test_v3_api.py]
    N759[agents.js]
    N760[auto-settings.js]
    N761[behavioral.js]
    N762[clusters.js]
    N763[compliance.js]
    N764[core.js]
    N765[dashboard.js]
    N766[events.js]
    N767[fact-detail.js]
    N768[feedback.js]
    N769[graph-core.js]
    N770[graph-filters.js]
    N771[graph-interactions.js]
    N772[graph-ui.js]
    N773[ide-status.js]
    N774[init.js]
    N775[learning.js]
    N776[lifecycle.js]
    N777[math-health.js]
    N778[memories.js]
    N779[modal.js]
    N780[patterns.js]
    N781[profiles.js]
    N782[recall-lab.js]
    N783[search.js]
    N784[settings.js]
    N785[timeline.js]
    N786[trust-dashboard.js]