graph TD
    N0[index.ts]
    N1[server.ts]
    N2[types.d.ts]
    N3[whatsapp.ts]
    N4[__init__.py]
    N5[__main__.py]
    N6[__init__.py]
    N7[context.py]
    N8[hook.py]
    N9[loop.py]
    N10[memory.py]
    N11[runner.py]
    N12[skills.py]
    N13[subagent.py]
    N14[__init__.py]
    N15[base.py]
    N16[cron.py]
    N17[filesystem.py]
    N18[mcp.py]
    N19[message.py]
    N20[registry.py]
    N21[shell.py]
    N22[spawn.py]
    N23[web.py]
    N24[__init__.py]
    N25[events.py]
    N26[queue.py]
    N27[__init__.py]
    N28[base.py]
    N29[dingtalk.py]
    N30[discord.py]
    N31[email.py]
    N32[feishu.py]
    N33[manager.py]
    N34[matrix.py]
    N35[mochat.py]
    N36[qq.py]
    N37[registry.py]
    N38[slack.py]
    N39[telegram.py]
    N40[wecom.py]
    N41[weixin.py]
    N42[whatsapp.py]
    N43[__init__.py]
    N44[commands.py]
    N45[models.py]
    N46[onboard.py]
    N47[stream.py]
    N48[__init__.py]
    N49[builtin.py]
    N50[router.py]
    N51[__init__.py]
    N52[loader.py]
    N53[paths.py]
    N54[schema.py]
    N55[__init__.py]
    N56[service.py]
    N57[types.py]
    N58[__init__.py]
    N59[service.py]
    N60[__init__.py]
    N61[anthropic_provider.py]
    N62[azure_openai_provider.py]
    N63[base.py]
    N64[openai_codex_provider.py]
    N65[openai_compat_provider.py]
    N66[registry.py]
    N67[transcription.py]
    N68[__init__.py]
    N69[network.py]
    N70[__init__.py]
    N71[manager.py]
    N72[init_skill.py]
    N73[package_skill.py]
    N74[quick_validate.py]
    N75[__init__.py]
    N76[__init__.py]
    N77[__init__.py]
    N78[evaluator.py]
    N79[helpers.py]
    N80[test_consolidate_offset.py]
    N81[test_context_prompt_cache.py]
    N82[test_evaluator.py]
    N83[test_gemini_thought_signature.py]
    N84[test_heartbeat_service.py]
    N85[test_loop_consolidation_tokens.py]
    N86[test_loop_cron_timezone.py]
    N87[test_loop_save_turn.py]
    N88[test_memory_consolidation_types.py]
    N89[test_onboard_logic.py]
    N90[test_runner.py]
    N91[test_session_manager_history.py]
    N92[test_skill_creator_scripts.py]
    N93[test_task_cancel.py]
    N94[test_base_channel.py]
    N95[test_channel_manager_delta_coalescing.py]
    N96[test_channel_plugins.py]
    N97[test_dingtalk_channel.py]
    N98[test_email_channel.py]
    N99[test_feishu_markdown_rendering.py]
    N100[test_feishu_post_content.py]
    N101[test_feishu_reply.py]
    N102[test_feishu_streaming.py]
    N103[test_feishu_table_split.py]
    N104[test_feishu_tool_hint_code_block.py]
    N105[test_matrix_channel.py]
    N106[test_qq_channel.py]
    N107[test_slack_channel.py]
    N108[test_telegram_channel.py]
    N109[test_weixin_channel.py]
    N110[test_whatsapp_channel.py]
    N111[test_cli_input.py]
    N112[test_commands.py]
    N113[test_restart_command.py]
    N114[test_config_migration.py]
    N115[test_config_paths.py]
    N116[test_cron_service.py]
    N117[test_cron_tool_list.py]
    N118[test_azure_openai_provider.py]
    N119[test_custom_provider.py]
    N120[test_litellm_kwargs.py]
    N121[test_mistral_provider.py]
    N122[test_provider_retry.py]
    N123[test_providers_init.py]
    N124[test_security_network.py]
    N125[test_exec_security.py]
    N126[test_filesystem_tools.py]
    N127[test_mcp_tool.py]
    N128[test_message_tool.py]
    N129[test_message_tool_suppress.py]
    N130[test_tool_validation.py]
    N131[test_web_fetch_security.py]
    N132[test_web_search_tool.py]