apply plugin: 'android-library'

dependencies {
    implementation fileTree(dir: 'bin', include: ['*.jar'])
    implementation fileTree(dir: 'libs', include: ['*.jar'])
}

android {
    namespace "com.parrotcarriers.audio"

    buildFeatures {
        buildConfig false
    }

    sourceSets {
        main {
            manifest.srcFile 'AndroidManifest.xml'
            res.srcDirs = ['res']
            assets.srcDirs = ['assets']
            jniLibs.srcDirs = ['libs']
        }
    }

    compileSdkVersion 36
    buildToolsVersion '34.0.0'
    defaultConfig {
        minSdkVersion 30
        targetSdkVersion 31
    }

    lintOptions {
        abortOnError false
    }
}
